version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: steam_key_db
    environment:
      POSTGRES_DB: steam_key_store
      POSTGRES_USER: store_admin
      POSTGRES_PASSWORD: 1243
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: ./backend
    container_name: steam_key_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data: