# Generated by Django 6.0.6 on 2026-06-14 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'В ожидании оплаты'), ('COMPLETED', 'Оплачено'), ('FAILED', 'Ошибка')], default='PENDING', max_length=20)),
                ('amount_paid', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='games.steamkey', verbose_name='Выданный ключ')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='games.game', verbose_name='Игра')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
