# Generated by Django 6.0.6 on 2026-06-13 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название игры')),
                ('description', models.TextField(blank=True, verbose_name='Описание игры')),
                ('price_stars', models.PositiveIntegerField(default=10, verbose_name='Цена в Telegram Stars')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='Ссылка на обложку')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SteamKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_value', models.CharField(max_length=255, unique=True, verbose_name='Ключ активации')),
                ('is_sold', models.BooleanField(default=False, verbose_name='Ключ продан')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keys', to='games.game', verbose_name='Игра')),
            ],
            options={
                'verbose_name': 'Steam Ключ',
                'verbose_name_plural': 'Steam Ключи',
            },
        ),
    ]
