# Generated by Django 6.0.6 on 2026-06-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('TEST', 'Тестовый платеж'), ('STARS', 'Telegram Stars')], default='TEST', max_length=50, verbose_name='Платежные метод')),
                ('transaction_id', models.CharField(blank=True, max_length=255, verbose_name='ID транзакции')),
                ('amount', models.PositiveIntegerField(verbose_name='Сумма транзакции (Stars)')),
                ('status', models.CharField(choices=[('PENDING', 'В обработке'), ('PAID', 'Успешно оплачено'), ('FAILED', 'Ошибка платежа')], default='PENDING', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
            },
        ),
    ]
