# Generated by Django 6.0.6 on 2026-06-14 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('TEST', 'Тестовый платёж'), ('STARS', 'Telegram Stars')], default='TEST', max_length=50, verbose_name='Провайдер оплаты'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'В ожидании'), ('PAID', 'Успешно оплачен'), ('FAILED', 'Ошибка оплаты')], default='PENDING', max_length=20, verbose_name='Статус'),
        ),
    ]
